export interface Image {
  height: number;
  id: string;
  url: string;
  width: number;
}

export interface Weight {
  imperial: string;
  metric: string;
}

export interface CatBreed {
  adaptability: number;
  affection_level: number;
  alt_names: string;
  cfa_url?: string;
  child_friendly: number;
  country_code: string;
  country_codes: string;
  description: string;
  dog_friendly: number;
  energy_level: number;
  experimental: number;
  grooming: number;
  hairless: number;
  health_issues: number;
  hypoallergenic: number;
  id: string;
  image: Image;
  indoor: number;
  intelligence: number;
  lap?: number;
  life_span: string;
  name: string;
  natural: number;
  origin: string;
  rare: number;
  reference_image_id: string;
  rex: number;
  shedding_level: number;
  short_legs: number;
  social_needs: number;
  stranger_friendly: number;
  suppressed_tail: number;
  temperament: string;
  vcahospitals_url?: string;
  vetstreet_url?: string;
  vocalisation: number;
  weight: Weight;
  wikipedia_url: string;
}

export const catsArray: CatBreed[] = [
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: '',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx',
    child_friendly: 3,
    country_code: 'EG',
    country_codes: 'EG',
    description:
      'The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.',
    dog_friendly: 4,
    energy_level: 5,
    experimental: 0,
    grooming: 1,
    hairless: 0,
    health_issues: 2,
    hypoallergenic: 0,
    id: 'abys',
    image: {
      height: 1445,
      id: '0XYvRd7oD',
      url: 'https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg',
      width: 1204,
    },
    indoor: 0,
    intelligence: 5,
    lap: 1,
    life_span: '14 - 15',
    name: 'Abyssinian',
    natural: 1,
    origin: 'Egypt',
    rare: 0,
    reference_image_id: '0XYvRd7oD',
    rex: 0,
    shedding_level: 2,
    short_legs: 0,
    social_needs: 5,
    stranger_friendly: 5,
    suppressed_tail: 0,
    temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian',
    vetstreet_url: 'http://www.vetstreet.com/cats/abyssinian',
    vocalisation: 1,
    weight: {
      imperial: '7  -  10',
      metric: '3 - 5',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_(cat)',
  },
  {
    adaptability: 5,
    affection_level: 4,
    alt_names: '',
    child_friendly: 4,
    country_code: 'GR',
    country_codes: 'GR',
    description:
      'Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.',
    dog_friendly: 4,
    energy_level: 3,
    experimental: 0,
    grooming: 3,
    hairless: 0,
    health_issues: 1,
    hypoallergenic: 0,
    id: 'aege',
    image: {
      height: 800,
      id: 'ozEvzdVM-',
      url: 'https://cdn2.thecatapi.com/images/ozEvzdVM-.jpg',
      width: 1200,
    },
    indoor: 0,
    intelligence: 3,
    life_span: '9 - 12',
    name: 'Aegean',
    natural: 0,
    origin: 'Greece',
    rare: 0,
    reference_image_id: 'ozEvzdVM-',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 4,
    stranger_friendly: 4,
    suppressed_tail: 0,
    temperament: 'Affectionate, Social, Intelligent, Playful, Active',
    vetstreet_url: 'http://www.vetstreet.com/cats/aegean-cat',
    vocalisation: 3,
    weight: {
      imperial: '7 - 10',
      metric: '3 - 5',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Aegean_cat',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: '',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx',
    child_friendly: 4,
    country_code: 'US',
    country_codes: 'US',
    description:
      'American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.',
    dog_friendly: 5,
    energy_level: 3,
    experimental: 0,
    grooming: 1,
    hairless: 0,
    health_issues: 1,
    hypoallergenic: 0,
    id: 'abob',
    image: {
      height: 951,
      id: 'hBXicehMA',
      url: 'https://cdn2.thecatapi.com/images/hBXicehMA.jpg',
      width: 1600,
    },
    indoor: 0,
    intelligence: 5,
    lap: 1,
    life_span: '11 - 15',
    name: 'American Bobtail',
    natural: 0,
    origin: 'United States',
    rare: 0,
    reference_image_id: 'hBXicehMA',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 3,
    stranger_friendly: 3,
    suppressed_tail: 1,
    temperament: 'Intelligent, Interactive, Lively, Playful, Sensitive',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail',
    vetstreet_url: 'http://www.vetstreet.com/cats/american-bobtail',
    vocalisation: 3,
    weight: {
      imperial: '7 - 16',
      metric: '3 - 7',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/American_Bobtail',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: '',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanCurl.aspx',
    child_friendly: 4,
    country_code: 'US',
    country_codes: 'US',
    description:
      'Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.',
    dog_friendly: 5,
    energy_level: 3,
    experimental: 0,
    grooming: 2,
    hairless: 0,
    health_issues: 1,
    hypoallergenic: 0,
    id: 'acur',
    image: {
      height: 964,
      id: 'xnsqonbjW',
      url: 'https://cdn2.thecatapi.com/images/xnsqonbjW.jpg',
      width: 1000,
    },
    indoor: 0,
    intelligence: 3,
    lap: 1,
    life_span: '12 - 16',
    name: 'American Curl',
    natural: 0,
    origin: 'United States',
    rare: 0,
    reference_image_id: 'xnsqonbjW',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 3,
    stranger_friendly: 3,
    suppressed_tail: 0,
    temperament:
      'Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/american-curl',
    vetstreet_url: 'http://www.vetstreet.com/cats/american-curl',
    vocalisation: 3,
    weight: {
      imperial: '5 - 10',
      metric: '2 - 5',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/American_Curl',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: 'Domestic Shorthair',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanShorthair.aspx',
    child_friendly: 4,
    country_code: 'US',
    country_codes: 'US',
    description:
      'The American Shorthair is known for its longevity, robust health, good looks, sweet personality, and amiability with children, dogs, and other pets.',
    dog_friendly: 5,
    energy_level: 3,
    experimental: 0,
    grooming: 1,
    hairless: 0,
    health_issues: 3,
    hypoallergenic: 0,
    id: 'asho',
    image: {
      height: 1200,
      id: 'JFPROfGtQ',
      url: 'https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg',
      width: 1600,
    },
    indoor: 0,
    intelligence: 3,
    lap: 1,
    life_span: '15 - 17',
    name: 'American Shorthair',
    natural: 1,
    origin: 'United States',
    rare: 0,
    reference_image_id: 'JFPROfGtQ',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 4,
    stranger_friendly: 3,
    suppressed_tail: 0,
    temperament: 'Active, Curious, Easy Going, Playful, Calm',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/american-shorthair',
    vetstreet_url: 'http://www.vetstreet.com/cats/american-shorthair',
    vocalisation: 3,
    weight: {
      imperial: '8 - 15',
      metric: '4 - 7',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/American_Shorthair',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: '',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanWirehair.aspx',
    child_friendly: 4,
    country_code: 'US',
    country_codes: 'US',
    description:
      'The American Wirehair tends to be a calm and tolerant cat who takes life as it comes. His favorite hobby is bird-watching from a sunny windowsill, and his hunting ability will stand you in good stead if insects enter the house.',
    dog_friendly: 5,
    energy_level: 3,
    experimental: 0,
    grooming: 1,
    hairless: 0,
    health_issues: 3,
    hypoallergenic: 0,
    id: 'awir',
    image: {
      height: 936,
      id: '8D--jCd21',
      url: 'https://cdn2.thecatapi.com/images/8D--jCd21.jpg',
      width: 1280,
    },
    indoor: 0,
    intelligence: 3,
    lap: 1,
    life_span: '14 - 18',
    name: 'American Wirehair',
    natural: 0,
    origin: 'United States',
    rare: 0,
    reference_image_id: '8D--jCd21',
    rex: 0,
    shedding_level: 1,
    short_legs: 0,
    social_needs: 3,
    stranger_friendly: 3,
    suppressed_tail: 0,
    temperament:
      'Affectionate, Curious, Gentle, Intelligent, Interactive, Lively, Loyal, Playful, Sensible, Social',
    vetstreet_url: 'http://www.vetstreet.com/cats/american-wirehair',
    vocalisation: 3,
    weight: {
      imperial: '8 - 15',
      metric: '4 - 7',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/American_Wirehair',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: 'Alley cat',
    child_friendly: 4,
    country_code: 'AE',
    country_codes: 'AE',
    description:
      'Arabian Mau cats are social and energetic. Due to their energy levels, these cats do best in homes where their owners will be able to provide them with plenty of playtime, attention and interaction from their owners. These kitties are friendly, intelligent, and adaptable, and will even get along well with other pets and children.',
    dog_friendly: 5,
    energy_level: 4,
    experimental: 0,
    grooming: 1,
    hairless: 0,
    health_issues: 1,
    hypoallergenic: 0,
    id: 'amau',
    image: {
      height: 1554,
      id: 'k71ULYfRr',
      url: 'https://cdn2.thecatapi.com/images/k71ULYfRr.jpg',
      width: 2048,
    },
    indoor: 0,
    intelligence: 3,
    life_span: '12 - 14',
    name: 'Arabian Mau',
    natural: 1,
    origin: 'United Arab Emirates',
    rare: 0,
    reference_image_id: 'k71ULYfRr',
    rex: 0,
    shedding_level: 1,
    short_legs: 0,
    social_needs: 3,
    stranger_friendly: 3,
    suppressed_tail: 0,
    temperament: 'Affectionate, Agile, Curious, Independent, Playful, Loyal',
    vcahospitals_url: '',
    vocalisation: 1,
    weight: {
      imperial: '8 - 16',
      metric: '4 - 7',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Arabian_Mau',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: 'Spotted Mist',
    child_friendly: 4,
    country_code: 'AU',
    country_codes: 'AU',
    description:
      'The Australian Mist thrives on human companionship. Tolerant of even the youngest of children, these friendly felines enjoy playing games and being part of the hustle and bustle of a busy household. They make entertaining companions for people of all ages, and are happy to remain indoors between dusk and dawn or to be wholly indoor pets.',
    dog_friendly: 5,
    energy_level: 4,
    experimental: 0,
    grooming: 3,
    hairless: 0,
    health_issues: 1,
    hypoallergenic: 0,
    id: 'amis',
    image: {
      height: 1165,
      id: '_6x-3TiCA',
      url: 'https://cdn2.thecatapi.com/images/_6x-3TiCA.jpg',
      width: 1231,
    },
    indoor: 0,
    intelligence: 4,
    lap: 1,
    life_span: '12 - 16',
    name: 'Australian Mist',
    natural: 0,
    origin: 'Australia',
    rare: 0,
    reference_image_id: '_6x-3TiCA',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 4,
    stranger_friendly: 4,
    suppressed_tail: 0,
    temperament: 'Lively, Social, Fun-loving, Relaxed, Affectionate',
    vocalisation: 3,
    weight: {
      imperial: '7 - 15',
      metric: '3 - 7',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Australian_Mist',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: 'Long-haired Siamese',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/Balinese.aspx',
    child_friendly: 4,
    country_code: 'US',
    country_codes: 'US',
    description:
      'Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ',
    dog_friendly: 5,
    energy_level: 5,
    experimental: 0,
    grooming: 3,
    hairless: 0,
    health_issues: 3,
    hypoallergenic: 1,
    id: 'bali',
    image: {
      height: 1000,
      id: '13MkvUreZ',
      url: 'https://cdn2.thecatapi.com/images/13MkvUreZ.jpg',
      width: 1600,
    },
    indoor: 0,
    intelligence: 5,
    life_span: '10 - 15',
    name: 'Balinese',
    natural: 0,
    origin: 'United States',
    rare: 0,
    reference_image_id: '13MkvUreZ',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 5,
    stranger_friendly: 5,
    suppressed_tail: 0,
    temperament: 'Affectionate, Intelligent, Playful',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/balinese',
    vetstreet_url: 'http://www.vetstreet.com/cats/balinese',
    vocalisation: 5,
    weight: {
      imperial: '4 - 10',
      metric: '2 - 5',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Balinese_(cat)',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: '',
    child_friendly: 4,
    country_code: 'US',
    country_codes: 'US',
    description:
      'The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. They love to be handled and cuddled up on the laps of their family members.',
    dog_friendly: 5,
    energy_level: 5,
    experimental: 1,
    grooming: 1,
    hairless: 1,
    health_issues: 1,
    hypoallergenic: 0,
    id: 'bamb',
    image: {
      height: 1030,
      id: '5AdhMjeEu',
      url: 'https://cdn2.thecatapi.com/images/5AdhMjeEu.jpg',
      width: 1296,
    },
    indoor: 0,
    intelligence: 5,
    lap: 1,
    life_span: '12 - 14',
    name: 'Bambino',
    natural: 0,
    origin: 'United States',
    rare: 0,
    reference_image_id: '5AdhMjeEu',
    rex: 0,
    shedding_level: 1,
    short_legs: 1,
    social_needs: 3,
    stranger_friendly: 3,
    suppressed_tail: 0,
    temperament: 'Affectionate, Lively, Friendly, Intelligent',
    vocalisation: 3,
    weight: {
      imperial: '4 - 9',
      metric: '2 - 4',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Bambino_cat',
  },
  {
    adaptability: 5,
    affection_level: 5,
    bidability: 3,
    cat_friendly: 4,
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/Bengal.aspx',
    child_friendly: 4,
    country_code: 'US',
    country_codes: 'US',
    description:
      "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
    dog_friendly: 5,
    energy_level: 5,
    experimental: 0,
    grooming: 1,
    hairless: 0,
    health_issues: 3,
    hypoallergenic: 1,
    id: 'beng',
    image: {
      height: 739,
      id: 'O3btzLlsO',
      url: 'https://cdn2.thecatapi.com/images/O3btzLlsO.png',
      width: 1100,
    },
    indoor: 0,
    intelligence: 5,
    lap: 0,
    life_span: '12 - 15',
    name: 'Bengal',
    natural: 0,
    origin: 'United States',
    rare: 0,
    reference_image_id: 'O3btzLlsO',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 5,
    stranger_friendly: 3,
    suppressed_tail: 0,
    temperament: 'Alert, Agile, Energetic, Demanding, Intelligent',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/bengal',
    vetstreet_url: 'http://www.vetstreet.com/cats/bengal',
    vocalisation: 5,
    weight: {
      imperial: '6 - 12',
      metric: '3 - 7',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Bengal_(cat)',
  },
  {
    adaptability: 5,
    affection_level: 5,
    alt_names: 'Sacred Birman, Sacred Cat Of Burma',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/Birman.aspx',
    child_friendly: 4,
    country_code: 'FR',
    country_codes: 'FR',
    description:
      'The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.',
    dog_friendly: 5,
    energy_level: 3,
    experimental: 0,
    grooming: 2,
    hairless: 0,
    health_issues: 1,
    hypoallergenic: 0,
    id: 'birm',
    image: {
      height: 814,
      id: 'HOrX5gwLS',
      url: 'https://cdn2.thecatapi.com/images/HOrX5gwLS.jpg',
      width: 1376,
    },
    indoor: 0,
    intelligence: 3,
    lap: 1,
    life_span: '14 - 15',
    name: 'Birman',
    natural: 0,
    origin: 'France',
    rare: 0,
    reference_image_id: 'HOrX5gwLS',
    rex: 0,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 4,
    stranger_friendly: 3,
    suppressed_tail: 0,
    temperament: 'Affectionate, Active, Gentle, Social',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/birman',
    vetstreet_url: 'http://www.vetstreet.com/cats/birman',
    vocalisation: 1,
    weight: {
      imperial: '6 - 15',
      metric: '3 - 7',
    },
    wikipedia_url: 'https://en.wikipedia.org/wiki/Birman',
  },
];
